create database UTP
go
use UTP

create table POSTULANTE(
ID INT NOT NULL PRIMARY KEY,
APELLIDOP VARCHAR(30) NOT NULL,
APELLIDOM VARCHAR(30) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
EDAD INT NOT NULL,
SEXO VARCHAR(1),
CARRERA VARCHAR(50)
)

INSERT INTO POSTULANTE VALUES(1000,'RODRIGUEZ','BERTO','GOHAN',18,'M','Ing. de Sistemas')
SELECT*FROM POSTULANTE